### ISSUE TITLE
地址不能用了,大佬

### ISSUE THREAD

**Issue by yzc90912** [mdddj/flutter_simple_shop#1]

**Comment by mdddj** [comment]
可以了，用itbug那个

**Comment by Johnnie-198312** [comment]
Performing hot restart...
Syncing files to device iPhone 11 Pro Max...
Restarted application in 1,319ms.
flutter: 进来了
flutter: json={"timeToken":"1609728035477"}
flutter: -----------------------------------------参数&MD5-------------------------------------
flutter: timeToken = 1609728035477
flutter: 773a32e9f70824a10a6d2effc7546c34
flutter: ---------------------------------------------------------------------------------
flutter: /api/v1/dtk/apis/categorys
flutter: dio请求出错:[-1],错误信息:连接超时,接口:/api/v1/dtk/apis/categorys
flutter: 进来了
flutter: json={"timeToken":"1609728045810"}
flutter: -----------------------------------------参数&MD5-------------------------------------
flutter: timeToken = 1609728045810
flutter: c9dc1ff016913b9219cf630b3a82d68d
flutter: ---------------------------------------------------------------------------------
flutter: /api/v1/dtk/apis/topic
flutter: dio请求出错:[-1],错误信息:连接超时,接口:/api/v1/dtk/apis/topic
[VERBOSE-2:ui_dart_state.cc(177)] Unhandled Exception: RangeError (index): Invalid value: Valid value range is empty: 0
#0      List.[] (dart:core-patch/growable_array.dart:177:60)



还是连接超时.
