### ISSUE TITLE
文件缺失？

### ISSUE THREAD

**Issue by 9191app** [mdddj/flutter_simple_shop#3]
#  dataoke_sdk:
#    path: ../plugins/dataoke_sdk
#  dd_models:
#    path: ../plugins/dataoke_sdk/dd_models
#  extended_text_field:
#    path: ../../hlx/github/extended_text_field
#  dd_check_plugin:
#    path: ../../hlx/github/dd_check_plugin
#  loading_more_list:
#    path: ../../hlx/github/loading_more_list

**Comment by mdddj** [comment]
可替换成pub.dev的依赖,但是现在服务器关闭了, 跑起来也进不去主页

**Comment by 9191app** [comment]
看来我来晚了
